services:
  msa-dev-db:
    image: postgres:14.1-alpine
    container_name: msa-dev-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=most-secure-auth
    ports:
      - '5433:5432'
    volumes: 
      - ~/dockervol/postgres/msa-dev:/var/lib/postgresql/data

  msa-test-db:
    image: postgres:14.1-alpine
    container_name: msa-test-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=most-secure-auth
    ports:
      - '5434:5432'

  msa-redis-service:
    container_name: msa-redis-service
    image: redis
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6380:6379'

  msa-test-redis-service:
    container_name: msa-test-redis-service
    image: redis
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6381:6379'
      